config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'
  
  get 'auth/:provider/callback', to: 'sessions#create'

  get 'auth/failure', to: redirect('/')

  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show, :a]

  root to: "home#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:owner, :date, :title, :message)
    end
end

app/controllers/home_controller.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'
	PAGE_URL ="http://www.sueurdemetal.com/ville-metal-bordeaux-33.htm" 

class HomeController < ApplicationController
  def show
  
   
  
  
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:Pseudo)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
     <%= f.hidden_field :owner, :value => current_user.id %> 
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Date</th>
      <th>Title</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.owner %></td>
        <td><%= article.date %></td>
        <td><%= article.title %></td>
        <td><%= article.message %></td>
        <td><%= link_to 'Show', article %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
  <%= link_to 'New Article', new_article_path %>
<% else %>
  <p>Please <%= link_to "Sign in", "/auth/google_oauth2", id: "sign_in" %> to add your own article !
  </p>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @article.owner %>
</p>

<p>
  <strong>Date:</strong>
  <%= @article.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @article.message %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/show.html.erb
	<% if current_user %>
		<body>
			
			
			
			
			<div class="container-fluid">
				
				<div class="row" id="menu">
					<div class="col-md-offset-4 col-md-4">
						<div class="input-group">
						  <span class="input-group-addon glyphicon glyphicon-search"  id="sizing-addon2"></span>
						  <input type="text" class="form-control" placeholder="Recherchez un pote, un groupe..." aria-describedby="sizing-addon2">
						</div>
					</div>
				</div>
				
				
				<div class="row" id="body">
			  
				  <div class="col-md-3 gauche">
					  
					<div class="welcome">Welcome <%=current_user.name %> </div>
					
					<ul>
						<li><a>Actus</a></li>
						<li><a>Groupes</a></li>
					</ul>
				  </div>
				  
				  <div class="col-md-6 corps">
					<div class="headcorps">Fil d'actualité</div>
						
						<div class="hidden">
						
						<%= 	require 'open-uri' 
								require 'nokogiri' 
							
								page = Nokogiri::HTML(open("http://www.sueurdemetal.com/ville-metal-bordeaux-33.htm" ), nil, 'ISO-8859-1')
								
								news_links = page.css('div#contenupage')
								
								#Recup des dates
								i=0
								dates = [] 
								for elem in news_links.css('h3') 
									dates[i] = elem.text
									i = i+1
								end
								
								#Recup des salles
								i=0
								salles = [] 
								for elem in news_links.css('p strong') 
									salles[i] = elem.text
									i = i+1
								end
								
								
								#Recup des groupes dans les concerts
								i=0
								concerts = [] 
								
								
									
								groupes = []
								
								concert = []
								concerts = []
								i=0
								
								for elem in dates
									concert[0] = elem
									concert[1] = salles[i]
									j=0
								
									a = news_links.css('table.texte tr table.texte')[i]

										 
									for o in a.css('strong')
									
										groupes[j] = o.text
										j = j+1
										
									end
									
									concert[2] = groupes
									
									groupes = []
									concerts[i] = concert
									
									concert = []
									i = i+1
									
								end
								
								 %>
							</div>
					<% i=0 %>	 
					<% for article in concerts %>			 
					<div class="article">
						<div class="titrenews">
							<h4> <%= article[0] %> - <%= article[1] %> </h4>
						</div>
						
						<div class="groupes">
							<ul>
							<% for groupe in article[2] %>
								<li> <%= groupe %> </li>
							<% end %>
							</ul>
						</div>
						<% i=i+1 %>
					</div>
					<% end %>
					
				  </div>
				  
				  <div class="col-md-3 droite">
					<ul>
						<li><a href="/users">Profil</a></li>
						<li><a>Photos</a></li>
						<li><a>Amis</a></li>
					</ul>
				  </div>
				  
			  </div>
			</div>
			
		</body>

		<% else %>

		  <div class="row entete">
			<div class="col-md-3" >
				<h3>Welcome !</h3>
				<h5>Please connect to see our beautiful work !</h5>
			</div>
		  </div>

		<% end %>
	
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareNDeath</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "style.css" %>	
  <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
</head>
<body>
	
	<header>
		<div class="container">
				<div class="row" id="entete">
			  
					<div class="col-md-3" id="welcome">
					</div>
					
					<div class="col-md-5" id="titre">
						<h1>Share'N DEATH</h1>
					</div>
					
					<div class="col-md-2 logo">
						<img href="/images/logo.jpg" id="logo" />
					</div>
				</div>  
				
			</div>
	</header>
	
	
    <div>
    <div id="main-container" class="container">
    
        <% if current_user %>
            Signed in as <strong><%= current_user.name %></strong>
            <div class="btn-group" role="group" aria-label="...">
                <%= link_to "Sign out", signout_path, id: "sign_out", :class => "btn btn-warning" %>
            </div>


        <% else %>
        <div class="signin">
			<%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", :class => "btn btn-primary" %>
        </div>
        <% end %>

        <%= yield %>

    </div>
    </div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Pseudo %><br>
    <%= f.text_field :Pseudo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Pseudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.Pseudo %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pseudo:</strong>
  <%= @user.Pseudo %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>